### ISSUE TITLE
Posibility to set deviceID?

### ISSUE THREAD

**Issue by railnation** [MobileAppTracking/air-plugin#10]
Hi, 

Does mat.setAndroidId(true); work? Yes it works.
Why is it impossible to set such an identifier?

How can I get or send the deviceID?

Best regards

**Comment by john-gu** [comment]
Hi, could you clarify what you are looking for? Are you looking for a deviceID getter?

The ANE provides "getAdvertisingId" to return the Apple Advertising Id/Google Advertising Id on iOS/Android, respectively.

setAndroidId tells the ANE to retrieve the Android ID automatically on Android devices in order to send to TUNE. Do you need a getter for this value in your code as well?

**Comment by railnation** [comment]
Hi, 

We have a problem to identify our player if he installs the game. Here is a sample of the data send to MAT:

"device_id":null,
"device_id_md5":null,
"device_id_sha1":null,
"device_id_sha256":null,
"os_id":"5b4736af57820ba0",

It would be nice if we can set the deviceID if the user first installs the app. Something for the air plugin like this one:

public void setDeviceId(final String deviceId) {
        pubQueue.execute(new Runnable() { public void run() {
            params.setDeviceId(deviceId);
        }});
    }

**Comment by john-gu** [comment]
Hi, I believe setUserId may be more applicable in this case for your user identifier:
https://github.com/MobileAppTracking/air-plugin/blob/master/actionscript/src/com/hasoffers/nativeExtensions/MobileAppTracker.as#L309

Device ID is mapped to the IMEI and expected to be consistent across all apps on a device.
